---
apiVersion: v1
kind: Pod
metadata:
  name: rss-site
  labels:
    app: web
spec:
  containers:
    - name: front-end
      image: registry.access.redhat.com/ubi8/ubi:8.0-122 
      command:
        - "/bin/bash"
        - "-c"
        - "while true; do ls /root/buildinfo/; sleep 30; done"
